remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Gottedsienst reform - Unsere ideen
description: Auf dieser Webseite erfahren sie unsere ideen zur reformierung der Kirche.
